language: node_js

node_js:
- "4.1"

addons:
  firefox: latest

before_install:
- npm install -g typescript bower webpack gulp karma-cli

install:
- npm install
- bower install

before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm test
