language: node_js

node_js:
- '4.1'

addons:
  firefox: latest

before_install:
- npm install -g typescript gulp karma-cli

install:
- npm install

before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run build
- npm test

notifications:
  slack:
    secure: elJ+BxAaZR5CLvmbpBB6vYq/WaRzjc+KWLFIaVddxtFJdWGpboDgUyvZASpsK/fhlg9qpZJKLzOi04ZkmHRp69sOGfjvvgc7X0UgEit8yKFcQAqH3F0ecVKeIEeXyd/K5jd/El5j07AjPluYgIp1wRCPeaayO9i8bOMcJWdMsnI9cUeGLz/h3V4gGWfXRcH6NEt+1Q5vOeJrRdEsOaIZP4zMuP0osnjmgV+Q2t4hIRdL3Kx5nmcBp31CbQK1hchnX2441jxsF3/HjTgZ09gIk6V8+9pdAXlhKeUeBG4Vl5diix5Kl4M34JPZn2rU3nMGl95Cnp7J/dMR1wjHnYKdlkeYnx74UBACJRhUNOVNXQJUGDDcoxipSO0haXrw2G4j0YuDC5tjQtrvbwZ4yad3gnCVMiAbvwGJaoVIErVxCENIuaCHzhpQvoDvqvsTxDP3C9r+9y6bKDgiVhRuegIUHscqXZoaYsLCdX7exypvkxn6fO3CqgX0au2HcI+gZNp8B0jV20uSx6jrGWIlHFWaxonK/PON6OTgIMUWMdfZ++VX43WEg1qRiU3S9/YZ+b2sUpKPGBzK+W7XXEIA/WWN/lVEUYwRadGzgs3NyMJ5I+MFsLQcf+CIwMXIZwn5cGZO4uPBOaX62gNgbjbKeAeWkdxO3FuC4KRh1Z28t0LyESs=

sudo: false
