version: 0.1.{build}

init:
- cmd: git config --global core.autocrlf false

environment:
  nodejs_version: 4.1.2

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install -g typescript webpack gulp karma-cli
  - npm install

build: off

test_script:
  - npm test

notifications:
- provider: Slack
  auth_token:
    secure: tKLbWuTVfs56ZON0AQmsECYIf+4ryvXM5deSAFVn0eDdAWYzdhArA4321WisPMPHprMKal7FujbPqDqyVgOsiw==
  channel: webgl
  on_build_success: true
  on_build_failure: true
  template: "<{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}> Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}"
